### ISSUE TITLE
[CircularProgress Indeterminate state] when value: null, it throws errors

### ISSUE THREAD

**Issue by iNetJoJo** [chakra-ui/zag#1352]
# 🐛 Bug report
```
Error: [Progress] Invalid value: null
    at validateContext (http://localhost:6006/vendors-node_modules_chakra-ui_layout_dist_chunk-2OOHT3W5_mjs-node_modules_chakra-ui_layout_d-3c734a.iframe.bundle.js:452:19)
    at Machine.executeActions (http://localhost:6006/vendors-node_modules_chakra-ui_utils_dist_chunk-O3SWHQEE_mjs-node_modules_zag-js_anatomy_dist-c28652.iframe.bundle.js:719:13)
    at new Machine (http://localhost:6006/vendors-node_modules_chakra-ui_utils_dist_chunk-O3SWHQEE_mjs-node_modules_zag-js_anatomy_dist-c28652.iframe.bundle.js:927:10)
    at createMachine (http://localhost:6006/vendors-node_modules_chakra-ui_utils_dist_chunk-O3SWHQEE_mjs-node_modules_zag-js_anatomy_dist-c28652.iframe.bundle.js:988:42)
    at machine (http://localhost:6006/vendors-node_modules_chakra-ui_layout_dist_chunk-2OOHT3W5_mjs-node_modules_chakra-ui_layout_d-3c734a.iframe.bundle.js:404:69)
    at CircularProgress (http://localhost:6006/components-feedback-CircularProgress-CircularProgress-stories.iframe.bundle.js:350:142)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_chakra-ui_hooks_dist_chunk-QP32JBMJ_mjs-node_modules_chakra-ui_react_dis-35516f.iframe.bundle.js:90215:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors-node_modules_chakra-ui_hooks_dist_chunk-QP32JBMJ_mjs-node_modules_chakra-ui_react_dis-35516f.iframe.bundle.js:95967:13)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_chakra-ui_hooks_dist_chunk-QP32JBMJ_mjs-node_modules_chakra-ui_react_dis-35516f.iframe.bundle.js:97551:16)
    at beginWork (http://localhost:6006/vendors-node_modules_chakra-ui_hooks_dist_chunk-QP32JBMJ_mjs-node_modules_chakra-ui_react_dis-35516f.iframe.bundle.js:105947:14)
```

on sandbox it does not render anything, only root.
    
```ts
const [state, send] = useMachine(
  progress.machine({
    value: null,
  }),
)
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/live/e383c2c5-c01d-4639-bfa7-94067ec70a3d

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
