### ISSUE TITLE
Testing Select with Jest gives dom.getContentEl().scrollTo is not a function.

### ISSUE THREAD

**Issue by veloware** [chakra-ui/zag#1697]
# 🐛 Bug report

When trying to run a test in Jest for the Select machine / component as it is in the docs, gives an error - 

```
dom.getContentEl(...)?.scrollTo is not a function
```

## 💥 Steps to reproduce

1. Copy the code from the Select docs
2. Create a basic Jest test that tries to open the content popover
3. See error

## 💻 Link to reproduction

https://stackblitz.com/edit/vitejs-vite-kkkgte?file=src%2FApp.spec.js

or if the link doesn't work - 

```
import * as select from '@zag-js/select';
import { normalizeProps, Portal, useMachine } from '@zag-js/react';
import { useId } from 'react';

const selectData = [
  { label: 'Nigeria', value: 'NG' },
  { label: 'Japan', value: 'JP' },
  { label: 'Korea', value: 'KO' },
  { label: 'Kenya', value: 'KE' },
  { label: 'United Kingdom', value: 'UK' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Uganda', value: 'UG' },
];

export function Temp() {
  const collection = select.collection({
    items: selectData,
    itemToString: (item) => item.label,
    itemToValue: (item) => item.value,
  });

  const [state, send] = useMachine(
    select.machine({
      id: useId(),
      collection,
    })
  );

  const api = select.connect(state, send, normalizeProps);

  return (
    <div {...api.getRootProps()}>
      <div {...api.getControlProps()}>
        <label {...api.getLabelProps()}>Label</label>
        <button {...api.getTriggerProps()}>{api.valueAsString || 'Select option'}</button>
      </div>

      <Portal>
        <div {...api.getPositionerProps()}>
          <ul {...api.getContentProps()}>
            {selectData.map((item) => (
              <li key={item.value} {...api.getItemProps({ item })}>
                <span>{item.label}</span>
                <span {...api.getItemIndicatorProps({ item })}>✓</span>
              </li>
            ))}
          </ul>
        </div>
      </Portal>
    </div>
  );
}
```

```
describe('Temp tests', () => {
  it('should render', async () => {
    render(<Temp />);
    
    const root = screen.getByRole('combobox');
    
    await userEvent.click(root);
   
  });
});

```

## 🧐 Expected behavior
It shouldn't error

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |       0.61.1     |
| Browser          |      Jest test      |
| Operating System |      Mac os      |

## 📝 Additional information

Stacktrace - 

```
dom.getContentEl(...)?.scrollTo is not a function
TypeError: dom.getContentEl(...)?.scrollTo is not a function
at scrollContentToTop (node_modules/@zag-js/select/src/select.machine.ts:622:35)
at Machine.executeActions (node_modules/@zag-js/core/src/machine.ts:560:9)
at Machine.performExitEffects (node_modules/@zag-js/core/src/machine.ts:682:5)
at Machine.stop (node_modules/@zag-js/core/src/machine.ts:219:10)
at node_modules/@zag-js/react/dist/index.js:244:15
at safelyCallDestroy (node_modules/react-dom/cjs/react-dom.development.js:3918:844)
at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:4058:1065)
at commitDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:4045:544)
at recursivelyTraverseMutationEffects (node_modules/react-dom/cjs/react-dom.development.js:4077:129)
at commitMutationEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:4099:213)
at commitMutationEffects (node_modules/react-dom/cjs/react-dom.development.js:4075:147)
at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:4583:21)
at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:4545:209)
at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:4440:97)
at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:2155:108)
at flushSync (node_modules/react-dom/cjs/react-dom.development.js:4453:66)
at ReactDOMRoot.Object.<anonymous>.ReactDOMHydrationRoot.unmount.ReactDOMRoot.unmount [as unmount] (node_modules/react-dom/cjs/react-dom.development.js:4913:1902)
  at Object.unmount (node_modules/@testing-library/react/dist/pure.js:145:12)
  at node_modules/@testing-library/react/dist/pure.js:271:12
  at node_modules/@testing-library/react/dist/act-compat.js:88:24
  at act (node_modules/react/cjs/react.development.js:2194:20)
  at node_modules/@testing-library/react/dist/act-compat.js:87:25
  at node_modules/@testing-library/react/dist/pure.js:270:28
  at Array.forEach (<anonymous>)
    at cleanup (node_modules/@testing-library/react/dist/pure.js:266:22)
    at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:31:25)
      at Promise.then.completed (node_modules/jest-circus/build/utils.js:289:28)
      at new Promise (<anonymous>)
        at callAsyncCircusFn (node_modules/jest-circus/build/utils.js:222:10)
        at _callCircusHook (node_modules/jest-circus/build/run.js:213:40)
        at async _runTest (node_modules/jest-circus/build/run.js:186:5)
        at async _runTestsForDescribeBlock (node_modules/jest-circus/build/run.js:86:9)
        at async _runTestsForDescribeBlock (node_modules/jest-circus/build/run.js:81:9)
        at async run (node_modules/jest-circus/build/run.js:26:3)
        at async runAndTransformResultsToJestFormat (node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:120:21)
        at async jestAdapter (node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
        at async runTestInternal (node_modules/jest-runner/build/runTest.js:367:16)
        at async runTest (node_modules/jest-runner/build/runTest.js:444:34)
```

**Comment by segunadebayo** [comment]
Please get ideas from Ark setup test file. We'll consider add it to the docs

https://github.com/chakra-ui/ark/blob/main/packages/react/src/setup-test.ts

**Comment by veloware** [comment]
thanks, I tried many different variations of whats in Ark, but I struggled to get it working, not sure if it is the difference between Jest and Vitest, or just something within my setup that im missing, nonetheless, I finally got it with - 

```
Object.defineProperty(global.window.Element.prototype, 'scrollTo', { value: () => {} });
```

(didnt have to use jsdom in the end, not sure why, im not overly familiar with mocking browser behaviour like this)
