### ISSUE TITLE
solidjs ssr with hydration "cannot read properties of null"

### ISSUE THREAD

**Issue by samuelstroschein** [chakra-ui/zag#385]
# 🐛 Bug report

Any zag component crashes in SolidJS during the hydration of a server-rendered component.  

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at index.page.tsx:14:3
    at Checkbox (index.page.tsx:20:34)
    at @solid-refresh:10:42
    at untrack (chunk-CGI4PW6R.js?v=14626c3e:447:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (chunk-CGI4PW6R.js?v=14626c3e:751:22)
    at updateComputation (chunk-CGI4PW6R.js?v=14626c3e:734:3)
    at createMemo (chunk-CGI4PW6R.js?v=14626c3e:253:5)
    at hmrCompWrapper (@solid-refresh:7:20)
    at chunk-CGI4PW6R.js?v=14626c3e:555:12
```

## 💥 Steps to reproduce

1. Go to https://stackblitz.com/edit/solidjs-templates-chv1jk?file=src/pages/index.page.tsx
2. Open (browser) inspect. 
3. The error should appear in the console right away. If not, refresh the preview.

## 💻 Link to reproduction

https://stackblitz.com/edit/solidjs-templates-chv1jk?file=src/pages/index.page.tsx

The `renderer` directory defines how the server renders a page and how the client hydrates it.

## 🧐 Expected behavior

No crash.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |        0.2     |
| Browser          |       Chrome     |
| Operating System |       MacOS     |

**Comment by samuelstroschein** [comment]
The SolidJS repo contains a similar issue https://github.com/solidjs/solid/issues/1188. It might be the case that this is a SolidJS bug

**Comment by segunadebayo** [comment]
Hi @samuelstroschein,

I opened the Stackblitz, and it seems to open correctly without crashing. I'm in doing something wrong? or did Solid.js fix it somehow?

<img width="1727" alt="CleanShot 2022-11-09 at 14 45 28@2x" src="https://user-images.githubusercontent.com/6916170/200810202-e44129b8-53e3-4075-a69f-353b340bfa84.png">

**Comment by anubra266** [comment]
@segunadebayo Solid js released a fix some hours ago.

**Comment by samuelstroschein** [comment]
Hi @segunadebayo, 

Sorry, the instructions were unclear. I meant to open inspect / the console once stackblitz finished loading. 

<img width="2060" alt="image" src="https://user-images.githubusercontent.com/35429197/200810885-748885cd-a61d-4ca2-8242-ca706240e56c.png">

@anubra266 which commit/PR in the solid repo are you referring to?

**Comment by anubra266** [comment]
@samuelstroschein https://github.com/solidjs/solid/issues/1188#issuecomment-1230860609

**Comment by samuelstroschein** [comment]
@anubra266 the bug still exists with >1.6 (after the PR merged). 

I was debating whether I open a bug in the solid repo. It seems like you believe (and I assumed so too) that the bug is Solid internal? If so, I'll go ahead and file a bug in the Solid repo.

**Comment by anubra266** [comment]
@samuelstroschein I changed the solid version to 1.5.2 in your stackblitz repro'. See the result


https://user-images.githubusercontent.com/30869823/200812268-36fbdc79-244f-4baf-9e67-0eb5221db633.mp4

**Comment by samuelstroschein** [comment]
@anubra266 interesting. i can't reproduce your result. setting solid to 1.5.2 still yields the same error. Can you send a link of your stackblitz fork?
https://user-images.githubusercontent.com/35429197/200813185-8f9ecee8-7d9b-41fb-a941-6cf68708b2b5.mov

**Comment by segunadebayo** [comment]
I just confirmed that it works as expected after upgrading to 1.5.2.

To get to work, though, you need to run `pnpm install` again in StackBlitz @samuelstroschein

**Comment by samuelstroschein** [comment]
@segunadebayo @anubra266 running the dev server with pnpm works for me too. running the dev server with npm leads to the crash. I'll investigate further. Zag does not seem to be the root cause.

**Comment by anubra266** [comment]
@samuelstroschein Yeah npm also crashes for me.
