### ISSUE TITLE
pnpm users should be warned about @zag-js/store duplication error

### ISSUE THREAD

**Issue by ceopaludetto** [chakra-ui/zag#761]
# 🚀 Feature request

When using `@zag-js/react` sometimes pnpm save two instances of `@zag-js/store` in node_modules(actually I don't know if this only occurs on monorepos), this breaks `valtio` behavior(as stated here https://github.com/pmndrs/valtio/discussions/706), throwing this error: 

<details>
  <summary>StackTrace</summary>
  <pre> error   proxyState is not iterable
  File:
    /Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@zag-js/react/node_modules/@zag-js/store/dist/index.mjs:235:51
  Code:
    234 |   }
    > 235 |   const [target, ensureVersion, createSnapshot] = proxyState;
          |                                                   ^
      236 |   return createSnapshot(target, ensureVersion(), handlePromise);
      237 | }
      238 | function ref(obj) {
  Stacktrace:
TypeError: proxyState is not iterable
    at snapshot (file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@zag-js/react/node_modules/@zag-js/store/dist/index.mjs:235:51)
    at file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@zag-js/react/dist/index.mjs:70:11
    at Object.useSyncExternalStore (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:67:8)
    at exports.useSyncExternalStore (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react/cjs/react.production.min.js:25:469)
    at useSnapshot (file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@zag-js/react/dist/index.mjs:51:24)
    at useMachine (file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@zag-js/react/dist/index.mjs:119:17)
    at usePressable (file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@ark-ui/react/pressable/use-pressable.mjs:14:25)
    at file:///Users/carlos/Documents/Projetos/Javascript/nen/node_modules/@ark-ui/react/pressable/pressable.mjs:25:30
    at Uc (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
    at Xc (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:75:395)
    at Z (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Xc (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:75:509)
    at Z (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Qc (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:87:219)
    at Immediate._onImmediate (/Users/carlos/Documents/Projetos/Javascript/nen/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:98:56)
    at process.processImmediate (node:internal/timers:476:21)</pre>
</details>

pnpm users should be warned in docs(and possibly in ark docs too) about the `@zag-js/store` duplication error. The fix is to force resolution of only one `@zag-js/store` package in node_modules:
```json
"pnpm": {
  "overrides": {
    "@zag-js/store": "^0.12.0"
  }
}
```

## 🧱 Problem Statement / Justification

This should be added to inform people about `valtio` limitation. We could add a FAQ or troubleshooting section?

**Comment by segunadebayo** [comment]
Good catch! I've gone ahead to update the docs.

**Comment by coopbri** [comment]
Thanks for the fix! This issue also occurs if you are using Yarn with the [pnpm linker](https://yarnpkg.com/configuration/yarnrc#nodeLinker), in  which case the solution is to use `resolutions` in `package.json`:


```json
  "resolutions": {
    "@zag-js/store": "^0.12.0"
  },
```

**Comment by AlphaNecron** [comment]
> Thanks for the fix! This issue also occurs if you are using Yarn with the [pnpm linker](https://yarnpkg.com/configuration/yarnrc#nodeLinker), in which case the solution is to use `resolutions` in `package.json`:
> 
> ```json
>   "resolutions": {
>     "@zag-js/store": "^0.12.0"
>   },
> ```

This issue occurs even with `node-module` as linker. However, this did the trick.
