### ISSUE TITLE
Getting error when adding Select for React via yarn

### ISSUE THREAD

**Issue by ipekli** [chakra-ui/zag#860]
# 🐛 Bug report

I'm getting following error when I run `yarn add @zag-js/select @zag-js/react`

`Error: Couldn't find package "@zag-js/visually-hidden@0.19.1" required by "@zag-js/select" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/USERNAME/.nvm/versions/node/v20.0.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/USERNAME/.nvm/versions/node/v20.0.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/USERNAME/.nvm/versions/node/v20.0.0/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/USERNAME/.nvm/versions/node/v20.0.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/bguen/.USERNAME/versions/node/v20.0.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

## 💥 Steps to reproduce

Run `yarn add @zag-js/select @zag-js/react`

## 🧐 Expected behavior

Packages must be installed when I run the yarn task.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.19.1          |
| Operating System |  MacOS, Node v20.0.0          |

**Comment by segunadebayo** [comment]
Something must be weird with yarn because the package exists in the registry, as you can see.

![CleanShot 2023-09-13 at 09 06 43@2x](https://github.com/chakra-ui/zag/assets/6916170/6804e5d0-c5fe-4ef1-ba21-1fcf4f7db098)

Please consider trying this again or use other package managers (npm, pnpm, bun)
